export class mm_customer {
  public brn_cd: string;
  public cust_cd: number;
  public cust_type: string;
  public title: string;
  public first_name: string;
  public middle_name: string;
  public last_name: string;
  public cust_name: string;
  public guardian_name: string;
  public cust_dt: Date;
  public old_cust_cd: string;
  public dt_of_birth: Date;
  public age: number;
  public sex: string;
  public marital_status: string;
  public catg_cd: number;
  public community: number;
  public caste: number;
  public permanent_address: string;
  public ward_no: number;
  public state: string;
  public dist: string;
  public pin: number;
  public vill_cd: string;
  public block_cd: string;
  public service_area_cd: string;
  public occupation: string;
  public phone: string;
  public present_address: string
  public farmer_type: string;
  public email: string;
  public monthly_income: number;
  public date_of_death: Date;
  public sms_flag: string;
  public status: string
  public pan: string;
  public nominee: string;
  public nom_relation: string
  public kyc_photo_type: string;
  public kyc_photo_no: string;
  public kyc_address_type: string;
  public kyc_address_no: string;
  public org_status: string;
  public org_reg_no: number;
  public extra_data: number;
  public created_by: string;
  public created_dt: Date;
  public modified_by: string;
  public modified_dt: Date;
  public acc_num: string;
}
